name: Gradle Build and Maven Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest


    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish Snapshot
        if: "github.ref_name == 'main'"
        run: ./gradlew clean build publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Release
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}  # Remove the 'refs/tags/' prefix
          ./gradlew clean build publish -Pproject_version=$TAG_NAME
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Check Pull Request
        if: "startsWith(github.ref, 'refs/pull/')"
        run: |
          ./gradlew clean build